connection_wait = 60

[login]
username = "填写学号"
password = "信息门户密码"
service = "校园网、南京移动、常州电信、常州联通"
wait_seconds = 3

[[connection]]
url = "http://www.msftncsi.com/ncsi.txt"
value = "Microsoft NCSI"

[webdriver]
chrome_path = "chrome-win64"
driver_path = "chromedriver.exe"
